// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file HelloWorldOne.cpp
 * This source file contains the definition of the described types in the IDL file.
 *
 * This file was generated by the tool gen.
 */

#ifdef _WIN32
// Remove linker warning LNK4221 on Visual Studio
namespace {
char dummy;
}  // namespace
#endif  // _WIN32

#include "HelloWorldOne.h"
#include <fastcdr/Cdr.h>

#include <fastcdr/exceptions/BadParamException.h>
using namespace eprosima::fastcdr::exception;

#include <utility>

HelloWorldOne::HelloWorldOne()
{
    // m_id com.eprosima.idl.parser.typecode.PrimitiveTypeCode@5891e32e
    m_id = 0;
    // m_type com.eprosima.idl.parser.typecode.PrimitiveTypeCode@cb0ed20
    m_type = 0;
    // m_subtype com.eprosima.idl.parser.typecode.PrimitiveTypeCode@8e24743
    m_subtype = 0;
    // m_message com.eprosima.idl.parser.typecode.StringTypeCode@74a10858
    m_message ="";

}

HelloWorldOne::~HelloWorldOne()
{




}

HelloWorldOne::HelloWorldOne(
        const HelloWorldOne& x)
{
    m_id = x.m_id;
    m_type = x.m_type;
    m_subtype = x.m_subtype;
    m_message = x.m_message;
}

HelloWorldOne::HelloWorldOne(
        HelloWorldOne&& x) noexcept 
{
    m_id = x.m_id;
    m_type = x.m_type;
    m_subtype = x.m_subtype;
    m_message = std::move(x.m_message);
}

HelloWorldOne& HelloWorldOne::operator =(
        const HelloWorldOne& x)
{

    m_id = x.m_id;
    m_type = x.m_type;
    m_subtype = x.m_subtype;
    m_message = x.m_message;

    return *this;
}

HelloWorldOne& HelloWorldOne::operator =(
        HelloWorldOne&& x) noexcept
{

    m_id = x.m_id;
    m_type = x.m_type;
    m_subtype = x.m_subtype;
    m_message = std::move(x.m_message);

    return *this;
}

bool HelloWorldOne::operator ==(
        const HelloWorldOne& x) const
{

    return (m_id == x.m_id && m_type == x.m_type && m_subtype == x.m_subtype && m_message == x.m_message);
}

bool HelloWorldOne::operator !=(
        const HelloWorldOne& x) const
{
    return !(*this == x);
}

size_t HelloWorldOne::getMaxCdrSerializedSize(
        size_t current_alignment)
{
    size_t initial_alignment = current_alignment;


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4) + 255 + 1;


    return current_alignment - initial_alignment;
}

size_t HelloWorldOne::getCdrSerializedSize(
        const HelloWorldOne& data,
        size_t current_alignment)
{
    (void)data;
    size_t initial_alignment = current_alignment;


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4) + data.message().size() + 1;


    return current_alignment - initial_alignment;
}

void HelloWorldOne::serialize(
        eprosima::fastcdr::Cdr& scdr) const
{

    scdr << m_id;
    scdr << m_type;
    scdr << m_subtype;
    scdr << m_message.c_str();

}

void HelloWorldOne::deserialize(
        eprosima::fastcdr::Cdr& dcdr)
{

    dcdr >> m_id;
    dcdr >> m_type;
    dcdr >> m_subtype;
    dcdr >> m_message;
}

/*!
 * @brief This function sets a value in member id
 * @param _id New value for member id
 */
void HelloWorldOne::id(
        uint32_t _id)
{
    m_id = _id;
}

/*!
 * @brief This function returns the value of member id
 * @return Value of member id
 */
uint32_t HelloWorldOne::id() const
{
    return m_id;
}

/*!
 * @brief This function returns a reference to member id
 * @return Reference to member id
 */
uint32_t& HelloWorldOne::id()
{
    return m_id;
}

/*!
 * @brief This function sets a value in member type
 * @param _type New value for member type
 */
void HelloWorldOne::type(
        uint32_t _type)
{
    m_type = _type;
}

/*!
 * @brief This function returns the value of member type
 * @return Value of member type
 */
uint32_t HelloWorldOne::type() const
{
    return m_type;
}

/*!
 * @brief This function returns a reference to member type
 * @return Reference to member type
 */
uint32_t& HelloWorldOne::type()
{
    return m_type;
}

/*!
 * @brief This function sets a value in member subtype
 * @param _subtype New value for member subtype
 */
void HelloWorldOne::subtype(
        uint32_t _subtype)
{
    m_subtype = _subtype;
}

/*!
 * @brief This function returns the value of member subtype
 * @return Value of member subtype
 */
uint32_t HelloWorldOne::subtype() const
{
    return m_subtype;
}

/*!
 * @brief This function returns a reference to member subtype
 * @return Reference to member subtype
 */
uint32_t& HelloWorldOne::subtype()
{
    return m_subtype;
}

/*!
 * @brief This function copies the value in member message
 * @param _message New value to be copied in member message
 */
void HelloWorldOne::message(
        const std::string& _message)
{
    m_message = _message;
}

/*!
 * @brief This function moves the value in member message
 * @param _message New value to be moved in member message
 */
void HelloWorldOne::message(
        std::string&& _message)
{
    m_message = std::move(_message);
}

/*!
 * @brief This function returns a constant reference to member message
 * @return Constant reference to member message
 */
const std::string& HelloWorldOne::message() const
{
    return m_message;
}

/*!
 * @brief This function returns a reference to member message
 * @return Reference to member message
 */
std::string& HelloWorldOne::message()
{
    return m_message;
}

size_t HelloWorldOne::getKeyMaxCdrSerializedSize(
        size_t current_alignment)
{
    size_t current_align = current_alignment;







    return current_align;
}

bool HelloWorldOne::isKeyDefined()
{
    return false;
}

void HelloWorldOne::serializeKey(
        eprosima::fastcdr::Cdr& scdr) const
{
    (void) scdr;
        
}
