#ifndef CDATABASE_IDL
#define CDATABASE_IDL

//需要做时间匹配的各种数据体都要继承该结构，如果包含以上所有类型的信息，则总共大概400多字节
struct CDataBase
{
    octet                                         eDataType;          // 数据体类型
    octet                                         eDataSourceType;    // 数据体来源类型
    unsigned long                                 unFrameId;          // 帧号
    map<octet, unsigned long long>                mapTimeStamp;       // 存放各个阶段各种数据的时间戳：ms
    map<octet, unsigned long>                     mapDelay;           // 存放各个阶段各种过程耗时信息：ms
    map<octet, float>                             mapFps;             // 存放各个阶段的各种数据的帧率：f/s
};

#endif